name: Run ETL Daily

on:
  schedule:
    - cron: '15 7 * * *'   # This runs at 7:00 UTC daily (adjust as needed)
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy psycopg2-binary

      - name: Download CSV files
        run: |
          curl -O https://your-storage.com/path/sales_data.csv
          curl -O https://your-storage.com/path/product_catalog.csv
          curl -O https://your-storage.com/path/fulfilment_data.csv

      - name: Run ETL Script
        run: python etl_pipeline.py
